#! /usr/bin/env bash

source config.sh
source nizzetup-core/menu.sh

# If we don't got any parameter we will do this interactively
if [ $# -eq 0 ]; then
    while [ 1 ]; do
        show_menu
    done
else
    for option in $@; do
        run_option $option
    done
fi
